### ISSUE TITLE
[chassis] minigraph_ptf_indices wrong in minigraph_facts on a multi-asic linecard.

### ISSUE THREAD

**Issue by mannytaheri** [Azure/sonic-mgmt#5214]
**Description**
After the change in https://github.com/Azure/sonic-mgmt/pull/5011/ the minigraph_ptf_indices in minigraphs facts on a mulit-asic card is wrong.

Our T2 min topology has the following ptf port mapping:
```
    ARISTA01T3:
      vlans:
        - "0.4@0"
        - "0.5@1"
      vm_offset: 0
    ARISTA03T3:
      vlans:
        - "0.8@2"
      vm_offset: 1
    ARISTA04T3:
      vlans:
        - "0.26@3"
        - "0.27@4"
      vm_offset: 2
    ARISTA06T3:
      vlans:
        - "0.23@5"
      vm_offset: 3

```
mg_facts returned from dut.get_extended_minigraph_facts() has the following minigraph_ptf_indices

```
{u'Ethernet8': 9, u'Ethernet9': 10, u'Ethernet2': 3, u'Ethernet3': 0, u'Ethernet0': 1, u'Ethernet1': 2, u'Ethernet6': 7, u'Ethernet7': 2, u'Ethernet4': 1, u'Ethernet5': 6, u'Ethernet22': 5, u'Ethernet18': 19, u'Ethernet19': 20, u'Ethernet14': 15, u'Ethernet15': 16, u'Ethernet16': 17, u'Ethernet17': 18, u'Ethernet10': 11, u'Ethernet11': 12, u'Ethernet12': 13, u'Ethernet35': 36, u'Ethernet-IB1': 38, u'Ethernet-IB0': 37, u'Ethernet32': 33, u'Ethernet33': 34, u'Ethernet30': 31, u'Ethernet31': 32, u'Ethernet29': 30, u'Ethernet28': 29, u'Ethernet34': 35, u'Ethernet21': 22, u'Ethernet20': 21, u'Ethernet23': 24, u'Ethernet13': 14, u'Ethernet25': 3, u'Ethernet24': 25, u'Ethernet27': 28, u'Ethernet26': 4}
```
As can be seen
-  'Ethernet4' has ptf port index of 1 - it should be 0. 
- 'Ethernet5' has ptf port index of 6 - should be 1.

Reverting this PR, we get the correct ptf port mapping.

This is causing several ptf tests to fail on a T2 chassis with multi-asic linecard. Specifically:
- test_arp_all
- ip_fwd
- voq_ipfwd

**Steps to reproduce the issue:**
1. With the latest sonic-mgmt run any of the above mentioned ptf related tests
2.
3.

**Describe the results you received:**
Get wrong ptf port mapping and thus causing failures.

**Describe the results you expected:**
Expect the ptf port mapping to be the consistent with what is defined in the topo file.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```
